/**
 * \file tree.h
 * \brief Tree class header.
 * \author Florian Galinier
 * \author Clément Simon
 * \version 0.2
 * \date 13/03/15
 *
 * Declaration of Tree class (used by Interpreter class).
 *
 */

#pragma once

#include <iostream>
#include <vector>
#include <utility>
#include <tuple>
#include "../model/value.h"


namespace stibbons {

	/**
	  * \class Tree
	  * \brief Class that will represent a syntaxic tree.
	  *
	  * This tree will be generated by syntaxic analyser and
	  * can be interpreted.
	  *
	  * \author Florian Galinier
	  * \author Clément Simon
	  */
	class Tree {
	private:
		std::pair<int,Value*> node;
		std::vector<Tree*>* sons;
		std::pair<int,int> position;
	public:
		/**
		 * Create a new tree from a token_type and a value
		 * \param token The kind of token that is used to create the node
		 * \param val The value (if needed) corresponding to the token
		 */
		Tree(int token = 0, Value* val=nullptr);

		/**
		 * Destroy a tree and his sons.
		 *
		 */
		virtual ~Tree();

		/**
		 * Test if the node is a leaf.
		 * \return true is current tree has no sons
		 */
		virtual bool isLeaf() const;

		/**
		 * Return current node.
		 * \return A pair of <token_type,Value> corresponding to current node
		 */
		virtual std::pair<int,Value*> getNode() const;

		/**
		 * Append the sons of t to the current node.
		 *
		 * \param t A Tree.
		 */ 
		void appendTree(Tree*);

		/**
		 * Create and append a son to current tree.
		 * \param token The kind of token that is used to create the son
		 * \param val The value (if needed) corresponding to the son's token
		 */
		virtual void addSon(int,Value*);

		/**
		 * Append a tree son to current tree.
		 * \param t The tree to append
		 */
		virtual void addSon(Tree*);

		/**
		 * Return all sons of current tree
		 * \return a vector that contains all sons of the Tree
		 */
		virtual std::vector<Tree*>* getSons() const;

		/**
		 * Return a son identify by his position
		 * \param pos the position of the needed son
		 * \return the requested son (Tree* type)
		 */
		virtual Tree* getSon(size_t pos=0) const;

		/**
		 * Set the position of the token in file
		 * \param pos a pair <line,column>
		 */
		virtual void setPosition(std::pair<int,int>);

		/**
		 * Return the position of the token of current node.
		 * \return a pair <line,column>
		 */
		virtual std::pair<int,int> getPosition() const;

		virtual void output(std::ostream&,std::string dec="") const;
	};

}

/*
 * Editor modelines  -  http://www.wireshark.org/tools/modelines.html
 *
 * Local variables:
 * c-basic-offset: 4
 * tab-width: 4
 * indent-tabs-mode: t
 * truncate-lines: 1
 * End:
 *
 * vim:set ft=cpp ts=4 sw=4 sts=4
 */
